# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - deividas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://deividas.azurewebsites.net//
        username: ${{ secrets.AzureAppService_ContainerUsername_141b263564f245588c0b3d16988b817f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e9cc52ab9b4348f99676e5b61a1607be }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: deividas.azurewebsites.net//${{ secrets.AzureAppService_ContainerUsername_141b263564f245588c0b3d16988b817f }}/index:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'deividas'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_55034d0ed5ca4d248783988dc7fc3445 }}
        images: 'deividas.azurewebsites.net//${{ secrets.AzureAppService_ContainerUsername_141b263564f245588c0b3d16988b817f }}/index:${{ github.sha }}'